# Site settings
title: grokify.github.io
email: johncwang@gmail.com
description: "Personal blog about product management, engineering, hacking, open-source, startups, etc."
baseurl: ""
url: "https://grokify.github.io"
twitter_username: grokify
github_username:  grokify

# Build settings
markdown: kramdown
permalink: pretty
excerpt_separator: "<!-- more -->"

gems:
  - jekyll-sitemap
